name: 
on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Please provide the exact branch name'     
        required: true
     
  #pull_request:
    #types: [closed]
    #branches:
     # - master

jobs:
  build:
   # if: | 
    #  github.event.pull_request.merged == true
    runs-on: ubuntu-20.04
    env:
      BRANCH_NAME: ${{ github.event.inputs.branch_name }}

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
        with:
          ref: master
      
      - name: branch name
        id: branch
        run: |
          feature=$(echo "${{ env.BRANCH_NAME}}" | cut -d "-" -f 2)
          echo "::set-output name=feature_name::$feature"
          echo "$feature"
      

      - name: building infinity
        run: |
          yarn install
          yarn run build
        shell: bash

      - name: creating index.html versioning i.e index-<tag#>
        run: |
          ls -al
        #  cp public/index.html public/index-feature-${{ steps.branch.outputs.feature_name }}
       # shell: bash
